# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Francisco García
# Description of the Site
description: Personal Website (under construction)
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: /assets/images/im.jpg

# Posibles imágenes
# /assets/images/im.jpg
# https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: 
facebook_username: 
twitter_username: 
instagram_username: 
linkedin_username: francisco-jose-garcia-garces
github_username:  FranGarcia94
youtube_channel_id: 
reddit_username:
behance_username: 
dribbble_username:
spotify_username: 

# Google Analytics
google-analytics: 

# Disqus # Servicio de alojamiento de comentarios de blog
disqus-shortname: 

# Name of the Author
author-name: Francisco García
# URL for the Image of the Author
author-image: https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png

# Imágenes para author-image
# /assets/images/foto_1.jpg
# https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_960_720.png

# 60 Words About the Author
author-about: Electrical engineer educated at the University of Almería with a specialty in renewable energies. My goal is to contribute to the development of a modern and optimized electrical system where clean energies play a leading role.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/FranGarcia94

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
